on:
    push:
        branches-ignore:
            - 'github-comments'
    pull_request:
        branches-ignore:
            - 'github-comments'

name: CI

jobs:
    build:
        name: Build

        runs-on: ubuntu-latest

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2

            -   name: "Set up Python 3.7"
                uses: actions/setup-python@v1
                with:
                    python-version: '3.7' # Semantic version range syntax or exact version of a Python version

            -   name: "Display Python version"
                run: python -c "import sys; print(sys.version)"

            -   name: "Install Sphinx dependencies"
                run: sudo apt-get install python-dev build-essential

            -   name: "Cache pip"
                uses: actions/cache@v2
                with:
                    path: ~/.cache/pip
                    key: ${{ runner.os }}-pip-${{ hashFiles('_build/.requirements.txt') }}
                    restore-keys: |
                        ${{ runner.os }}-pip-

            -   name: "Install Sphinx + requirements via pip"
                run: pip install -r _build/.requirements.txt

            -   name: "Build documentation"
                run: make -C _build SPHINXOPTS="-nqW -j auto" html

    build-php:
        name: Symfony doc builder

        runs-on: ubuntu-latest

        continue-on-error: true

        steps:
            - name: "Checkout"
              uses: actions/checkout@v2

            - name: "Set-up PHP"
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.2
                  coverage: none
                  tools: "composer:v2"

            - name: Get composer cache directory
              id: composercache
              working-directory: _build
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: "Install dependencies"
              working-directory: _build
              run: composer install --prefer-dist --no-progress

            - name: "Build the docs"
              working-directory: _build
              run: php build.php -vvv

    doctor-rst:
        name: DOCtor-RST

        runs-on: ubuntu-latest

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2

            -   name: "Create cache dir"
                run: mkdir .cache

            -   name: "Extract base branch name"
                run: echo "##[set-output name=branch;]$(echo ${GITHUB_BASE_REF:=${GITHUB_REF##*/}})"
                id: extract_base_branch

            -   name: "Cache DOCtor-RST"
                uses: actions/cache@v2
                with:
                    path: .cache
                    key: ${{ runner.os }}-doctor-rst-${{ steps.extract_base_branch.outputs.branch }}

            -   name: "Run DOCtor-RST"
                uses: docker://oskarstark/doctor-rst
                with:
                    args: --short --error-format=github --cache-file=/github/workspace/.cache/doctor-rst.cache
